acf_catalog.catalog.*:
  type: config_entity
  label: 'Catalog config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    connection:
      type: string
    entities:
      type: sequence
      label: 'Child entities'
      sequence:
        type: sequence
        label: 'Entity Type'
        sequence:
          type: mapping
          label: 'Entity Bundle'
          mapping:
            key:
              type: string
              label: 'Entity Reference Key'
            data:
              type: sequence
              label: 'Entity Field Data'
              sequence:
                type: sequence
                label: 'Entity Field'
                sequence:
                  type: string
                  label: 'Field Property'